CREATE TABLE USERS_TICKET
(
    USER_LOGIN varchar(50) REFERENCES USERS (login) ON UPDATE CASCADE ON DELETE CASCADE,
    TICKET_ID  int REFERENCES TICKET (id) ON UPDATE CASCADE,
    CONSTRAINT user_ticket_pkey PRIMARY KEY (USER_LOGIN, TICKET_ID)
);


CREATE TABLE USERS_ROLE
(
    USER_LOGIN varchar(50) REFERENCES USERS (login) ON UPDATE CASCADE ON DELETE CASCADE,
    ROLE_ID  int REFERENCES ROLE (id) ON UPDATE CASCADE,
    CONSTRAINT user_role_pkey PRIMARY KEY (USER_LOGIN, ROLE_ID)
);